name: Build-Release-Pipeline

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.13.1]

    steps:
      - name: Download Code from Repository
        uses: actions/checkout@v4.1.5
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install NPM for Build
        run: npm install
      
      - name: Run NPM Build
        run: npm run build
      
      - name: Share Artifact Inside Workflow
        uses: actions/upload-artifact@v4
        with:
          name: hbreact
          path: build

  deploy_local:
    needs: build
    runs-on: hpzbookg9

    steps: 
    - name: Stop Website
      run: |
        # Stop the IIS website
        C:\Windows\System32\inetsrv\appcmd stop site /site.name:"HouseBids Website"

    - name: Prepare local folders
      run: |       
        Remove-Item 'c:\pub\hbreact_bak1' -Recurse -ErrorAction Ignore
        Remove-Item 'c:\pub\hbreact_bak' -Recurse -ErrorAction Ignore
        ren c:\pub\hbreact hbreact_bak
        md c:\pub\hbreact

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: hbreact
        path: c:\pub\hbreact

    - name: Start Website
      run: |
        # Start the IIS website
        C:\Windows\System32\inetsrv\appcmd start site /site.name:"HouseBids Website"

        
  deploy_remote:
    needs: deploy_local
    runs-on: win2019dc03
    environment:
      name: IIS_Environment.Prod

    steps: 
    - name: Stop Website
      run: |
        # Stop the IIS website
        C:\Windows\System32\inetsrv\appcmd stop site /site.name:"HouseBids Website"

    - name: Prepare local folders
      run: |       
        Remove-Item 'c:\pub\hbreact_bak1' -Recurse -ErrorAction Ignore
        Remove-Item 'c:\pub\hbreact_bak' -Recurse -ErrorAction Ignore
        ren c:\pub\hbreact hbreact_bak
        md c:\pub\hbreact

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: hbreact
        path: c:\pub\hbreact

    - name: Start Website
      run: |
        # Start the IIS website
        C:\Windows\System32\inetsrv\appcmd start site /site.name:"HouseBids Website"
 