name: Release Pipeline

on:
  workflow_dispatch:

jobs:
  deploy_local:
    runs-on: hpzbookg9

    steps:
    - name: Stop Website
      run: |
        # Stop the IIS website
        C:\Windows\System32\inetsrv\appcmd stop site /site.name:"HouseBids Website"

    - name: Prepare local folders
      run: |
        Remove-Item 'c:\pub\hbreact_bak1' -Recurse -ErrorAction Ignore
        Remove-Item 'c:\pub\hbreact_bak' -Recurse -ErrorAction Ignore
        ren c:\pub\hbreact hbreact_bak
        md c:\pub\hbreact

    - name: Download Release Asset
      run: |
        $url = (Invoke-RestMethod -Uri "https://api.github.com/repos/roncalw/HouseBids-React/releases/tags/v1.0.0").assets | Where-Object { $_.name -eq "build.zip" } | Select-Object -ExpandProperty browser_download_url
        Invoke-WebRequest -Uri $url -Headers @{Authorization = "token $env:GITHUB_TOKEN"} -OutFile "c:\pub\hbreact\build.zip"
    
    - name: Unzip Artifact and Copy Contents
      shell: powershell
      run: |
          Expand-Archive -Path 'c:\pub\hbreact\build.zip' -DestinationPath 'c:\pub\hbreact'
          Move-Item -Path 'c:\pub\hbreact\build\*' -Destination 'c:\pub\hbreact' -Force -Verbose
          Remove-Item -Path 'c:\pub\hbreact\build' -Force -Recurse -Verbose
          Remove-Item -Path 'c:\pub\hbreact\build.zip' -Force -Verbose

    - name: Start Website
      run: |
        # Start the IIS website
        C:\Windows\System32\inetsrv\appcmd start site /site.name:"HouseBids Website"

  deploy_remote:
    needs: deploy_local
    runs-on: win2019dc03
    environment:
      name: IIS_Environment.Prod

    steps:
    - name: Stop Website
      run: |
        # Stop the IIS website
        C:\Windows\System32\inetsrv\appcmd stop site /site.name:"HouseBids Website"

    - name: Prepare local folders
      run: |
        Remove-Item 'c:\pub\hbreact_bak1' -Recurse -ErrorAction Ignore
        Remove-Item 'c:\pub\hbreact_bak' -Recurse -ErrorAction Ignore
        ren c:\pub\hbreact hbreact_bak
        md c:\pub\hbreact

    - name: Download Release Asset
      run: |
        $url = (Invoke-RestMethod -Uri "https://api.github.com/repos/roncalw/HouseBids-React/releases/tags/v1.0.0").assets | Where-Object { $_.name -eq "build.zip" } | Select-Object -ExpandProperty browser_download_url
        Invoke-WebRequest -Uri $url -Headers @{Authorization = "token $env:GITHUB_TOKEN"} -OutFile "c:\pub\hbreact\build.zip"
        
    - name: Unzip Artifact and Copy Contents
      shell: powershell
      run: |
          Expand-Archive -Path 'c:\pub\hbreact\build.zip' -DestinationPath 'c:\pub\hbreact'
          Move-Item -Path 'c:\pub\hbreact\build\*' -Destination 'c:\pub\hbreact' -Force -Verbose
          Remove-Item -Path 'c:\pub\hbreact\build' -Force -Recurse -Verbose
          Remove-Item -Path 'c:\pub\hbreact\build.zip' -Force -Verbose

    - name: Start Website
      run: |
        # Start the IIS website
        C:\Windows\System32\inetsrv\appcmd start site /site.name:"HouseBids Website"

