name: Release Pipeline

on:
  workflow_dispatch:

jobs:
  deploy_local:
    runs-on: self-hosted

    steps: 
    - name: Stop IIS website
      shell: pwsh
      uses: actions/github-script@v4
      with:
        script: |
          # Ensure the IIS module is imported
          if (-not (Get-Module -Name IISAdministration -ListAvailable)) {
              Import-Module IISAdministration
          }

          # Stop the IIS site
          Stop-IISSite -Name 'HouseBids Website' -Confirm:$false


    - name: Prepare local folders
      run: |       
        Remove-Item 'c:\pub\hbreact_bak1' -Recurse -ErrorAction Ignore
        Remove-Item 'c:\pub\hbreact_bak' -Recurse -ErrorAction Ignore
        ren c:\pub\hbreact hbreact_bak
        md c:\pub\hbreact

    - name: Download artifact
      uses: actions/download-artifact@v4.1.7
      with:
        name: hbreact
        path: c:\pub\hbreact

    - name: Start Website
      shell: pwsh
      run: Start-IISSite -Name "HouseBids Website"

        
  deploy_remote:
    needs: deploy_local
    runs-on: self-hosted
    environment:
      name: IIS_Environment.Prod

    steps: 
    - name: Stop Website
      shell: pwsh
      run: Stop-IISSite -Name "HouseBids Website" -Confirm:$false

    - name: Prepare local folders
      run: |       
        Remove-Item '\\WIN2019DC03\c$\pub\hbreact_bak1' -Recurse -ErrorAction Ignore
        Remove-Item '\\WIN2019DC03\c$\pub\hbreact_bak' -Recurse -ErrorAction Ignore
        ren \\WIN2019DC03\c$\pub\hbreact hbreact_bak
        md \\WIN2019DC03\c$\pub\hbreact

    - name: Download artifact
      uses: actions/download-artifact@v4.1.7
      with:
        name: hbreact
        path: \\WIN2019DC03\c$\pub\hbreact

    - name: Start Website
      shell: pwsh
      run: Start-IISSite -Name "HouseBids Website"
 