on:
  workflow_dispatch:

jobs:
  deploy_local:
    runs-on: self-hosted

    steps: 
    - name: Prepare local folders
      run: |       
        Remove-Item 'c:\pub\hbreact_bak1' -Recurse -ErrorAction Ignore
        Remove-Item 'c:\pub\hbreact_bak' -Recurse -ErrorAction Ignore
        ren c:\pub\hbreact hbreact_bak
        md c:\pub\hbreact

    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: Buid Pipline.ynl
        name: build
        path: c:\pub\hbreact
        
        
