name: Release Pipeline

on:
  workflow_dispatch:

jobs:
  deploy_local:
    runs-on: self-hosted

    steps: 
    - name: Stop Website
      shell: pwsh
      # Note: Had to import the IIS module to make this work on my machine ... Import-Module IISAdministration ... had to do this because the default powershell on my computer is version 7
      run: Start-Process -FilePath powershell.exe -ArgumentList "-NoProfile -ExecutionPolicy Bypass -Command `"Stop-IISSite -Name 'HouseBids Website' -Confirm:`$false`"" -Verb RunAs -WindowStyle Hidden

    - name: Prepare local folders
      run: |       
        Remove-Item 'c:\pub\hbreact_bak1' -Recurse -ErrorAction Ignore
        Remove-Item 'c:\pub\hbreact_bak' -Recurse -ErrorAction Ignore
        ren c:\pub\hbreact hbreact_bak
        md c:\pub\hbreact

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: hbreact
        path: c:\pub\hbreact
        run-id: 9213401993

    - name: Start Website
      shell: pwsh
      run: Start-Process -FilePath powershell.exe -ArgumentList "-NoProfile -ExecutionPolicy Bypass -Command `"Start-IISSite -Name 'HouseBids Website'`"" -Verb RunAs -WindowStyle Hidden

        
  deploy_remote:
    needs: deploy_local
    runs-on: self-hosted
    environment:
      name: IIS_Environment.Prod

    steps: 
    - name: Stop Website
      shell: pwsh
      run: Start-Process -FilePath powershell.exe -ArgumentList "-NoProfile -ExecutionPolicy Bypass -Command `"Stop-IISSite -Name 'HouseBids Website' -Confirm:`$false`"" -Verb RunAs -WindowStyle Hidden

    - name: Prepare local folders
      run: |       
        Remove-Item '\\WIN2019DC03\c$\pub\hbreact_bak1' -Recurse -ErrorAction Ignore
        Remove-Item '\\WIN2019DC03\c$\pub\hbreact_bak' -Recurse -ErrorAction Ignore
        ren \\WIN2019DC03\c$\pub\hbreact hbreact_bak
        md \\WIN2019DC03\c$\pub\hbreact

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: hbreact
        path: \\WIN2019DC03\c$\pub\hbreact
        run-id: 9213401993

    - name: Start Website
      shell: pwsh
      run: Start-Process -FilePath powershell.exe -ArgumentList "-NoProfile -ExecutionPolicy Bypass -Command `"Start-IISSite -Name 'HouseBids Website'`"" -Verb RunAs -WindowStyle Hidden
 