name: Release Pipeline

on:
  workflow_dispatch:

jobs:
  deploy_local:
    runs-on: hpzbookg9

    steps:
    - name: Stop Website
      run: |
        # Stop the IIS website
        C:\Windows\System32\inetsrv\appcmd stop site /site.name:"HouseBids Website"

    - name: Prepare local folders
      run: |
        Remove-Item 'c:\pub\hbreact_bak1' -Recurse -ErrorAction Ignore
        Remove-Item 'c:\pub\hbreact_bak' -Recurse -ErrorAction Ignore
        ren c:\pub\hbreact hbreact_bak
        md c:\pub\hbreact

    - name: Download Release Asset
      run: |
        curl -L \
        -H "Accept: application/octet-stream" \
        -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        "$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -s https://api.github.com/repos/roncalw/HouseBids-React/releases/tags/v1.0.0 | jq -r '.assets[] | select(.name == "build.zip") | .url')"
        --output c:\pub\hbreact\build.zip

    - name: Unzip Artifact
      shell: cmd
      run: |
        tar -xf c:\pub\hbreact\build.zip -C c:\pub\hbreact

    - name: Start Website
      run: |
        # Start the IIS website
        C:\Windows\System32\inetsrv\appcmd start site /site.name:"HouseBids Website"

  deploy_remote:
    needs: deploy_local
    runs-on: win2019dc03
    environment:
      name: IIS_Environment.Prod

    steps:
    - name: Stop Website
      run: |
        # Stop the IIS website
        C:\Windows\System32\inetsrv\appcmd stop site /site.name:"HouseBids Website"

    - name: Prepare local folders
      run: |
        Remove-Item 'c:\pub\hbreact_bak1' -Recurse -ErrorAction Ignore
        Remove-Item 'c:\pub\hbreact_bak' -Recurse -ErrorAction Ignore
        ren c:\pub\hbreact hbreact_bak
        md c:\pub\hbreact

    - name: Download Release Asset
      uses: actions/download-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        owner: roncalw
        repo: roncalw/HouseBids-React
        tag: v1.0.0
        name: build.zip
        path: c:\pub\hbreact

    - name: Unzip Artifact
      shell: cmd
      run: |
        tar -xf c:\pub\hbreact\build.zip -C c:\pub\hbreact

    - name: Start Website
      run: |
        # Start the IIS website
        C:\Windows\System32\inetsrv\appcmd start site /site.name:"HouseBids Website"

